names:
- rider
- motorcycle
- person
- car
- truck
- traffic sign
- vehicle fallback
- animal
- autorickshaw
- bus
- bicycle
- traffic light
- caravan
- train
- trailer
nc: 15
path: /raid/biplab/souravr/honda/detection_benchmark/data/IDD_Detection
test: /raid/biplab/souravr/honda/detection_benchmark/data/IDD_Detection/test.txt
train: /raid/biplab/souravr/honda/detection_benchmark/data/IDD_Detection/train.txt
val: /raid/biplab/souravr/honda/detection_benchmark/data/IDD_Detection/val.txt
